[program:{{ environ }}-{{ job_type }}]
stopasgroup=true
stopsignal=QUIT
autostart=true
autorestart=true
directory=/opt/repo/{{ job_type }}/{{ environ }}/target/release/
command=/bin/sh -c "cp -f /opt/repo/{{ job_type }}/{{ environ }}/environment.toml /opt/repo/{{ job_type }}/{{ environ }}/target/release/environment.toml && exec /opt/repo/{{ job_type }}/{{ environ }}/target/release/smartstudio-server"
stdout_logfile=/var/log/{{ job_type }}/stdout-{{ environ }}-{{ job_type }}.log
stderr_logfile=/var/log/{{ job_type }}/stderr-{{ environ }}-{{ job_type }}.log
startretries=3
user=root
environment=deploy_env="{{ env }}",HOME="/mnt/local-ssd", RUST_LOG=info,live_view_timing=info,smartstudio_server=info
