mod common;

async fn create_dv_for_templates(server: &axum_test::TestServer) -> String {
    let dv_id = "dv-tpl-canary";
    server
        .post("/dataviews")
        .json(&serde_json::json!({
            "id": dv_id,
            "display_name": "Template Canary View",
            "contract": { "grpc_service": "tpl_canary", "grpc_method": "list_tpl_canary" }
        }))
        .await;
    dv_id.to_string()
}

/// Canary: proto file comment contains "Generated from SmartStudio".
/// Turns RED after Tera templates are updated in Task 13.
#[tokio::test]
async fn generated_proto_contains_smartstudio_comment() {
    let (server, _tmp) = common::setup_server().await;
    let dv_id = create_dv_for_templates(&server).await;

    let resp = server
        .post(&format!("/generate/dataview/{dv_id}/preview"))
        .await;
    resp.assert_status_ok();
    let body: serde_json::Value = resp.json();
    let files = body["files"].as_object().unwrap();
    let proto_content = files
        .iter()
        .find(|(k, _)| k.ends_with(".proto"))
        .map(|(_, v)| v.as_str().unwrap_or(""))
        .expect("no .proto file in preview response");

    assert!(
        proto_content.contains("Generated from SmartStudio"),
        "proto file does not contain 'Generated from SmartStudio'"
    );
}

/// Canary: service.rs comment contains "Generated by SmartStudio".
/// Turns RED after Tera templates are updated in Task 13.
#[tokio::test]
async fn generated_service_rs_contains_smartstudio_comment() {
    let (server, _tmp) = common::setup_server().await;
    let dv_id = create_dv_for_templates(&server).await;

    let resp = server
        .post(&format!("/generate/dataview/{dv_id}/preview"))
        .await;
    resp.assert_status_ok();
    let body: serde_json::Value = resp.json();
    let service_content = body["files"]["src/service.rs"]
        .as_str()
        .expect("src/service.rs not in preview response");

    assert!(
        service_content.contains("Generated by SmartStudio"),
        "src/service.rs does not contain 'Generated by SmartStudio'"
    );
}
